muiriswoulfe/NuGet-Transitive-Dependency-Finder

- .github/workflows/build.yml
- .github/workflows/release.yml
Enhancing all existing GitHub Actions by:
- Adding job names, to enhance appearance.
- Adding extra spacing in the YAML definitions, to enhance readability.
- Making small internal job name changes, for alignment with the new external-facing names.
- No job names were present, resulting in the code names appearing in the interface.
- There was little spacing in the YAML, making long jobs difficult to comprehend.
- Names are present for all jobs.
- A consistent one-line gap has been added between each job step.
The new job names mean that PR validations must be updated, or it will become impossible to merge new PRs.
All GitHub Actions were run successfully after making this change.
> GitHub Actions: Naming & Formatting

- .github/workflows/build.yml
Connect [SonarCloud](https://sonarcloud.io/) to GitHub Actions to perform additional validations.
The code was not validated using SonarCloud.
The code is now being thoroughly validated using SonarCloud.
No code changes.
The project was built successfully via the GitHub Actions.
> Onboard SonarCloud

- .editorconfig
- .github/workflows/build.yml
- .github/workflows/release.yml
- src/Directory.Build.props
- src/NuGetTransitiveDependencyFinder/NuGetTransitiveDependencyFinder.csproj
Creating a GitHub Action for pushing releases to NuGet.org and the GitHub NuGet repository.
No NuGet packages were released.
The NuGet package and the NuGet symbols package are now released automatically whenever a new release is created.
None
Validated that the new GitHub Action works correctly, as well as ensuring that the contents of the NuGet package are valid.
> Creating publish to NuGet GitHub Action

- src/NuGetTransitiveDependencyFinder.ConsoleApp/Program.cs
Addressing a very minor issue identified by SonarCloud regarding an unused expression value.
No behavior changes.
No breaking changes.
> Addressing SonarCloud issue

- .github/workflows/release.yml
Updating the release GitHub Actions to fix issues following migration to .NET 5
The release action was failing.
The release action should succeed.
None
This was tested locally but will need to be tested again after merging.
> Updating release action

- .github/workflows/release.yml
- .github/workflows/release_manual.yml
Updating manual release pipeline, to resolve previous breaks.
> Updating Release Manual GitHub Action

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/support-request.md
- .github/pull_request_template.md
- .github/workflows/build.yml
- .github/workflows/release.yml
- README.md
- src/global.json
Updating .NET Core to the latest version (v5.0.1) and the GitHub Actions Markdown Link Checker.
> Updating .NET Core & GitHub Actions

- .editorconfig
Updating .editorconfig from RehanSaeed/EditorConfig project from 2.0.0 to 2.0.1 to leverage the latest fixes. This upgrade also allows for the removal of some project-specific overrides.
> Updating .editorconfig

- src/Directory.Build.props
- src/NuGetTransitiveDependencyFinder/NuGetTransitiveDependencyFinder.csproj
Updating all NuGet dependencies to the latest releases.
There are no behavioral changes between the previous and current releases. The changes are merely to the NuGet dependencies, which have no visible impact. Updating brings in improvements and security fixes.
There are no breaking changes.
These changes were validated locally via test projects. No behaviour changes were detected.
> Updating NuGet dependencies

- src/global.json
Updating the `rollForward` logic within `global.json` to use the latest available version of .NET. This will allow for newer versions to be proactively tested via GitHub Actions, highlighting whether code modifications are required.
The `rollForward` logic was set to `latestFeature`.
The `rollForward` logic is now set to `latestMajor`, allowing far more .NET updates to be brought in.
For now, there are no breaking changes. In the future, when .NET 6 or greater is released, these updates will be automatically picked up if installed.
The changes were built locally and via the GitHub Actions. No changes in functionality occurred as the change currently has no impact on the actual .NET version used.
More information of `global.json` can be found at …
> Updating global.json rollForward logic

- .github/workflows/build.yml
Enhancing the Build GitHub Action to test the logic across three platforms -- macOS, Ubuntu and Windows -- to reduce regression risk further.
The test logic was run only on Ubuntu.
The test logic is now run on macOS and Windows as well as Ubuntu.
None, as all existing logic works across platforms.
The updated GitHub Action was run successfully for all platforms.
> Adding cross-platform testing

- src/Directory.Build.props
- src/global.json
Updating .NET to the latest release – 5.0.103 – along with all updated dependencies.
No behavior changes are expected.
The .NET update may affect project consumers.
The changes were validated against a test project and via unit testing.
> Updating .NET & Dependencies

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
Updating dependabot.yml to better handle package updates. This change:
- Adds support for GitHub Actions.
- Adds additional metadata to Dependabot PRs.
- Adds coverage for more package files.
- Switches to version numbers for GitHub Actions, given the availability of Dependabot support for automatically updating these.
None, as this change only applies to GitHub infrastructure.
Full testing will only be possible after this update is parsed by GitHub's Dependabot infrastructure. In the interim, the changes have been validated by the GitHub Actions build.
> Enhancing Dependabot configuration

- .editorconfig
Updating the .editorconfig file to v2.1.0 following its release today.
> Updating .editorconfig to v2.1.0

- global.json
Updating .NET Core to 5.0.201.
> Updating .NET Core to 5.0.201

- global.json
Updating .NET to v5.0.301 (aka v5.0.7).
> Updating .NET to v5.0.301

- .editorconfig
- .gitignore
Updating .editorconfig and .gitignore to the latest available versions.
> Updating .editorconfig and .gitignore

- .github/dependabot.yml
Updating the Dependabot configuration to re-enable updates.
> Updating Dependabot configuration

- .editorconfig
Updating .editorconfig from v2.1.0 to v3.0.0, following its release.
Release details can be located at <https://github.com/RehanSaeed/EditorConfig/releases/tag/3.0.0>.
> Updating .editorconfig to v3.0.0

- .editorconfig
Updating .editorconfig to v4.1.0. Release notes for the change can be found at <https://github.com/RehanSaeed/EditorConfig/releases/tag/4.1.0>.
Build continues to work both locally and via GitHub Actions.
> Updating .editorconfig to v4.1.0

- .github/workflows/build.yml
Adding the [PR Metrics](https://github.com/marketplace/actions/pr-metrics-1-4-0) build task to the build pipeline.
> XS✔ ◾ Adding PR Metrics build task

- global.json
Updating .NET to v6.0.5 (aka v6.0.300).
> XS✔ ◾ Updating .NET to v6.0.5/v6.0.300

- global.json
> XS✔ ◾ Updating .NET to v6.0.301

- global.json
Updating .NET to v6.0.302 (aka v6.0.7).
> XS✔ ◾ Updating .NET to v6.0.302

- global.json
Updating .NET to the latest release – v6.0.400.
> XS✔ ◾ Updating .NET to v6.0.400

- global.json
> XS✔ ◾ Updating .NET to v6.0.401

- global.json
Updating .NET to v6.0.402, the most recent version.
> XS✔ ◾ Updating .NET to v6.0.402

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/build.yml
- .github/workflows/release.yml
- .vscode/launch.json
- README.md
- global.json
- src/Directory.Build.props
- src/Shared/Properties/AssemblyInfo.cs
- src/Tests/NuGetTransitiveDependencyFinder.TestUtilities/Logging/LogEntry.cs
- src/Tests/NuGetTransitiveDependencyFinder.UnitTests.ConsoleApp/Process/ProgramRunnerUnitTests.cs
- src/Tests/NuGetTransitiveDependencyFinder.UnitTests.ConsoleApp/Resources/StringsUnitTests.cs
- src/Tests/NuGetTransitiveDependencyFinder.UnitTests/TransitiveDependencyFinderUnitTests.cs
Updating .NET to v7.0. This also includes an update to the Java dependency within the build pipeline, and improves the GitHub codespace settings.
> XS✔ ◾ Updating .NET to v7.0

- global.json
> XS✔ ◾ Update .NET to v7.0.102

- .github/workflows/build.yml
Switching from an older JSON validation action that will soon become obsolete to a newer one that is easier to use and provides more comprehensive and future-proofed analysis.
No behavioral changes.
No breaking changes.
Tested via the pipeline. Manual validation confirms that the checks before and after the change remain the same.
> XS✔ ◾ Updating JSON Validation

- global.json
> XS✔ ◾ Updating .NET to v7.0.200

- global.json
> XS✔ ◾ Updating .NET to v7.0.202

- global.json
> XS✔ ◾ Updating .NET to v7.0.203

- global.json
> XS✔ ◾ Updating .NET to v7.0.304

- global.json
> XS✔ ◾ Updating .NET to v7.0.305

- .vscode/settings.json
Adding `settings.json`, which is autogenerated by Visual Studio Code C# extensions.
File was not present and would be automatically regenerated whenever the solution folder was opened within Visual Studio Code.
File is now present.
None
None, as this has no effect on the build or the project.
> XS✔ ◾ VS Code: Adding settings.json

- .github/workflows/build.yml
Enhancing the Build workflow to automatically close Dependabot PRs on a successful build.
Successful Dependabot builds required manual merging.
Successful Dependabot builds will not be automatically merged.
None, as the changes will be validated before being merged.
Pipeline cannot be tested until next Dependabot build is created and the status of that build checked.
> XS✔ ◾ Automatically merging Dependabot builds

- .github/workflows/build.yml
Updating Dependabot PRs to be automatically signed off, allowing automatic commits if the build checks pass.
> XS✔ ◾ Dependabot PR automatically sign-off

- src/Product/NuGetTransitiveDependencyFinder/ProjectAnalysis/DependencyGraph.cs
Fixing the recently introduced MSBuild check.
> XS⚠️ ◾ Fixing MSBuild check

- .github/workflows/build.yml
Refining the build to remove superfluous tasks.
> XS✔ ◾ Refining build

- NuGet.config
Refining NuGet owners to remove superfluous owner.
> XS✔ ◾ Refining NuGet owners

- global.json
> XS✔ ◾ Updating .NET to v7.0.401

- global.json
> XS✔ ◾ Updating .NET to v7.0.402

- global.json
> XS✔ ◾ Updating .NET to v7.0.403

- .github/workflows/build.yml
Onboarding the `fastify/github-action-merge-dependabot` GitHub action to support auto-merge and auto-approve for Dependabot PRs.
> XS✔ ◾ Enabling auto-merge and auto-approve for Dependabot

- .github/workflows/build.yml
Changing the tokens used for auto-approving the Dependabot builds.
> XS✔ ◾ Build: Correcting Auto-Approve

- .github/workflows/build.yml
This pull request includes a minor change to the `.github/workflows/build.yml` file. The change modifies the `SONARCLOUD FINALIZATION – SonarCloud Analyze` job, specifically altering the `run` command to use `sonar.token` instead of `sonar.login` for the `dotnet-sonarscanner` end command.
> XS✔ ◾ Update SonarCloud build workflow

- global.json
> XS✔ ◾ Updating .NET to v8.0.301

- global.json
> XS✔ ◾ Updating .NET to v8.0.302

- global.json
> XS✔ ◾ Updating .NET to v8.0.303

- global.json
> XS✔ ◾ Updating .NET to v8.0.400

- global.json
> XS✔ ◾ Updating .NET to v8.0.401
