.github/workflows/build.yml
Adding the following security validations to the build GitHub Action, to run on every commit and every PR:
- [CodeQL](https://securitylab.github.com/tools/codeql)
- [Security Scan](https://github.com/marketplace/actions/security-and-licence-scan)
CodeQL runs as a discrete job as it takes a relatively long time to run (approximately 10 minutes). In contrast, Security Scan runs in the existing validation job. This division helps to keep the overall running time down, while minimizing GitHub Action costs.
No security validation was present.
The build GitHub Action includes both CodeQL and Security Scan validations.
The new validations will become required checks for merging a PR.
All GitHub Actions were run successfully after making this change.
=> GitHub Actions: CodeQL & Security Scan

.github/workflows/build.yml, .github/workflows/release.yml, src/Directory.Build.props, src/NuGet.TransitiveDependency.Finder.ConsoleApp/NuGet.TransitiveDependency.Finder.ConsoleApp.csproj, src/NuGet.TransitiveDependency.Finder.Library/NuGet.TransitiveDependency.Finder.Library.csproj, src/NuGet.TransitiveDependency.Finder.Library/ProjectAnalysis/DotNetRunner.cs, src/global.json
Updating the project to the newly release .NET 5. This allows the latest libraries, performance enhancements, validation, and other improvements to be leveraged.
The project used .NET Core 3.1 and .NET Standard 2.0.
The project now uses .NET 5 throughout. There should be no behavioral changes resulting from this upgrade.
There should be no breaking changes resulting from this upgrade.
The application was run under typical circumstances. No changes to functionality or behavior were detected.
=> Upgrading to .NET 5

src/NuGet.TransitiveDependency.Finder.ConsoleApp/Output/Writer.cs, src/NuGet.TransitiveDependency.Finder.ConsoleApp/Program.cs, src/NuGet.TransitiveDependency.Finder.Library/ProjectAnalysis/Assets.cs
This PR resolves some remaining CodeQL-identified issues around unused `using` directives.
There were unused `using` directives in some files.
There are now no unused `using` directives in any files.
This change does not in any way affect functionality as the removed code was entirely unused.
The app was tested and behaved identically to before. In addition, no issues were detected during GitHub Action code scanning.
=> Fixing CodeQL-identified issues

.github/workflows/build.yml
Updating the `gaurav-nelson/github-action-markdown-link-check` GitHub Action from 1.0.9 to 1.0.10 to leverage the latest fixes.
=> Updating gaurav-nelson/github-action-markdown-link-check

.github/linters/.jscpd.json
Following the addition of JSCPD to Super-Linter, validation has failed due to repetition within the `release.yml` GitHub Action definition. However, this repetition cannot be resolved due to the lack of facilities for avoiding duplication within GitHub Actions.
The "Release" GitHub Action failed when linting `release.yml`.
The "Release" GitHub Action no longer fails.
No breaking changes.
This change was tested via the "Release" GitHub Action, which passed successfully.
Information on JSCPD configuration can be found at <https://github.com/kucherenko/jscpd/tree/master/packages/jscpd>, while information on Super-Linter can be found at <https://github.com/github/super-linter>.
=> Fixing Super-Linter Validation

.github/ISSUE_TEMPLATE/config.yml, .github/SUPPORT.md
Adding a `config.yml` file as documented at <https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser>. This file acts as an Issue template chooser within GitHub.
No `config.yml` file was present. The default GitHub template choosing logic applied.
The template choosing logic from `config.yml` now applies. This adds a link to the support discussions page and removes the option of creating a blank issue.
None, as this has no impact on the project code.
The template chooser was tested using a private repo.
=> Adding config.yml

.github/workflows/build.yml
Adding the [Application Inspector GitHub Action](https://github.com/microsoft/ApplicationInspector-Action/) to the build action, to gain greater insight into the APIs and features of the project as it progresses.
The Application Inspector was not present in the build action.
The Application Inspector is now present in the build action.
None, as this only impacts validation performed as part of the build action. It has no impact on the project or its build process.
The build action was run successfully.
=> Adding Application Inspector to Build Action

.github/linters/.jscpd.json, .github/workflows/build.yml
Reducing duplication within the "Build" GitHub Action, by avoiding repeatedly replacing the placeholder version with the latest tag. This serves to enhance maintainability and improve build performance.
The suppression for the JSCPD logic within the Super-Linter has also been updated.
Each stage within the "Build" GitHub Action replaced the placeholder version with the latest tag, even when this update was not directly used within that build step.
The superfluous replacement of the version numbers has been removed.
The build pipeline has been modified, but in a way that should be transparent to consumers.
The build pipeline was validated to run successfully and generate the expected outputs with these changes in place.
=> Reducing duplication within "Build" GitHub Action

.github/workflows/build.yml
Enabling SonarCloud test coverage by modifying parameters passed via SonarQube invocation.
This change also includes small modifications to the ordering of the build operations in order to minimize overall running times.
SonarCloud test coverage was previously at zero and failed to reflect the recent addition of unit tests.
SonarCloud test coverage now correctly reflects the actual project test coverage.
None, as this only modifies the build parameters invoking SonarCloud.
The build action was successfully ran.
=> Enabling SonarCloud test coverage

NuGet.config
Changing the NuGet packages location to avoid flagging of CodeQL issues within dependencies.
The NuGet packages were placed within the "packages" folder inside the solution folder.
The NuGet packages are now placed within the "..\packages\NuGetTransitiveDependencyFinder" folder inside the solution folder (i.e. from one level below the solution folder).
None, from the perspective of external callers as these changes merely impact the build process.
These changes were validated to run locally as well as through the GitHub Actions.
=> Changing NuGet packages location

global.json
Updating .NET Core from SDK 5.0.202 to SDK 5.0.203 (AKA 5.0.6) via `global.json`. See <https://github.com/dotnet/core/releases/tag/v5.0.6> for the release or <https://github.com/dotnet/core/issues/6247> for the associated GitHub issue.
This change results in no behavior changes.
This change results in no breaking changes as the update is only a minor security update.
Unit tests have been verified to run successfully following the update.
=> Updating .NET Core to 5.0.6

.github/workflows/build.yml
Disabling CodeCov within the **Build** GitHub Action for PRs created by Dependabot. This change is being made to stop unnecessary runs of CodeCov, which fail to correct detect code coverage for these PRs.
CodeCov would run for Dependabot builds but always detect 0% code coverage.
CodeCov will not run for Dependabot builds.
No breaking changes, as no code changes have been made.
The **Build** GitHub Action has been verified to continue to run correctly for normal PR builds. It will be verified that the changes made result in the correct behavior for Dependabot PRs when the next Dependabot PR is created.
=> Disabling codecov for dependabot PRs

.github/dependabot.yml
Updating the Dependabot configuration to remove the restriction on the number of PRs that can be opened.
=> Updating Dependabot configuration

global.json
Updating .NET Core to SDK v5.0.302, aka [v5.0.8](https://github.com/dotnet/core/releases/tag/v5.0.8), which was released today.
=> Updating .NET Core to SDK v5.0.302

.github/workflows/build.yml, global.json
Updating .NET from v5.0.302 to v5.0.400 (aka v5.0.9), following its release.
Release details can be located at <https://github.com/dotnet/core/releases/tag/v5.0.9>.
This change also updates the Java SDK dependency, used by SonarCloud within the Build GitHub Action, from v16.0.1 to v16.0.2.
=> Updating .NET to v5.0.400

global.json
Updating .NET Core to v5.0.401 (v5.0.10) following its release. Release notes can be found at <https://github.com/dotnet/core/releases/tag/v5.0.10>.
=> Updating .NET Core to v5.0.401

src/Product/NuGetTransitiveDependencyFinder/ProjectAnalysis/DependencyFinder.cs
Without this change, only package references are considered. With this change, project references are considered as well.
Given the following example:
```
A
-> B (project)
-> C (project)
-> X (package)
B
-> C (project)
-> X (package)
C
-> X (package)
```
This fix now marks project C and package X as transitive when scanning project A, because it is also referenced by project B.
Project references are ignored. 
Project references are considered.
No, the API remains the same.
Without fix:
```
Commencing analysis...
Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
Determining projects to restore...
Writing A/j2wlqag5.tis
Determining projects to restore...
All projects are up-to-date for restore.
Determining projects to …
```
=> Use dependencies from assets file

src/Product/NuGetTransitiveDependencyFinder.ConsoleApp/Output/DependencyWriter.cs, src/Product/NuGetTransitiveDependencyFinder/Output/Dependency.cs, src/Product/NuGetTransitiveDependencyFinder/ProjectAnalysis/DependencyFinder.cs, src/Product/NuGetTransitiveDependencyFinder/PublicAPI.Shipped.txt
This PR also includes #149, which is necessary for this to work.
This fix keeps track of references to a dependency.
Given the following example:
```
A
-> B (project)
-> C (project)
-> X (package)
B
-> C (project)
-> X (package)
C
-> X (package)
```
When scanning project A, this fix:
- marks B as a 'provider' of C
- marks B and C as a 'provider' of X
- marks C and X as transitive
The logic for top-level dependencies has been slightly altered. This means that for a dependency to be transitive, it must have at least one 'provider'.
Providers were not listed, and so were project dependencies.
Providers are shown, and so are project dependencies.
The public API contains a new method:
```diff
+NuGetTransitiveDependencyFinder.Output.Dependency.Via.get -> …
```
=> Keep track of dependency providers

.github/workflows/build.yml, global.json
Updating .NET to the latest release, v6.0.201.
This change also removes a superfluous installaton of .NET v5 for SonarQube, which was previously required for compatibility reasons. It also upgrades the version of Java used by SonarQube.
=> Updating .NET to v6.0.201

.github/workflows/build.yml, global.json
Updating .NET to the latest release, v6.0.202.
This change also updates the Java build dependency to the latest version, v18.0.0.
=> Updating .NET to v6.0.202

.github/workflows/build.yml, src/CodeAnalysisDictionary.xml, src/Product/NuGetTransitiveDependencyFinder.ConsoleApp/NuGetTransitiveDependencyFinder.ConsoleApp.csproj
This PR adds the metadata for distributing this application as a .NET tool: https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create
If uploaded to NuGet, this allows one to use this application more easily, since it would then be installable using `dotnet tool install --global nugettransitivedependencyfinder.consoleapp` and usable with `dotnet transitive-dependency-finder`.
I did a suggestion for the CLI name, but let me know if I have to change something. I also added additional metadata based on [this](https://github.com/dotnet-outdated/dotnet-outdated/blob/master/src/DotNetOutdated/DotNetOutdated.csproj) project.
N/a
N/a
Package installs as a tool.
N/a
N/a
N/a
=> Add metadata to pack as tool

.github/CODEOWNERS, .github/dependabot.yml, .github/workflows/dependabot.yml
Adding a Dependabot build for automatically approving and merging Dependabot pull requests, assuming the build completes successfully.
Dependabot PRs had to be manually merged.
Dependabot PRs will be automatically merged to `main` if the build completes.
=> XS✔ ◾ Adding Dependabot Build

.github/workflows/build.yml
Fixing CodeQL & PR Metrics permissions within build pipeline.
In certain cases, CodeQL & PR Metrics had insufficient permissions and would fail to run successfully.
CodeQL now has the following permissions and should always run successfully.
```YAML
security-events: write
```
PR Metrics now has the following permissions and should also always run successfully.
```YAML
pull-requests: write
statuses: write
```
None.
Changes were successful run through the GitHub Actions pipelines.
=> XS✔ ◾ Workflow: Fixing CodeQL & PR Metrics permissions

.github/workflows/build.yml
Updating the Dependabot-only build to auto-merge Dependabot PRs where possible.
Dependabot build would fail, claiming that it was not running as part of a Git repo.
Dependabot build should succeed as Git code is checked out.
=> XS✔ ◾ Fixing Dependabot build

.vscode/settings.json, src/Tests/NuGetTransitiveDependencyFinder.TestUtilities/Globalization/AllCulturesBaseAttributeDiscoverer.cs, src/Tests/NuGetTransitiveDependencyFinder.TestUtilities/Globalization/AllCulturesBaseTestCase.cs, src/Tests/NuGetTransitiveDependencyFinder.TestUtilities/Globalization/AllCulturesFactAttribute.cs, src/Tests/NuGetTransitiveDependencyFinder.TestUtilities/Globalization/AllCulturesFactAttributeDiscoverer.cs, src/Tests/NuGetTransitiveDependencyFinder.TestUtilities/Globalization/AllCulturesFactTestCase.cs, src/Tests/NuGetTransitiveDependencyFinder.TestUtilities/Globalization/AllCulturesTheoryAttribute.cs, src/Tests/NuGetTransitiveDependencyFinder.TestUtilities/Globalization/AllCulturesTheoryAttributeDiscoverer.cs, src/Tests/NuGetTransitiveDependencyFinder.UnitTests/Utilities/NuGetLoggerUnitTests.cs
Refining the design of the xUnit test discoverers to reflect best practices and ensure all requirements for the test discoverers are met.
Partially addresses issue #29.
All tests would run, but "dotnet test -t" would not list tests in assemblies with the custom test attributes, which made testing using IDEs difficult.
All tests run and "dotnet test -t" lists all tests. In addition, more modern practices have been employed, with redundant logic removed.
None
Tests discovered locally via "dotnet test -t" and then run. Tests also run through GitHub Actions.
=> XS✔ ◾ xUnit: Refining test discoverers

.devcontainer/Dockerfile
Updating Dockerfile for Github Codespaces to .NET 8.0.
The Dockerfile specified .NET 7.0.
The Dockerfile now specifies .NET 8.0.
=> XS✔ ◾ Updating Dockerfile to .NET 8.0

.github/workflows/build.yml, global.json
This pull request includes a change to the GitHub Actions workflow configuration to adjust permissions for the `validate-lint` job.
Permissions adjustment:
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L433-R436): Modified the `permissions` for the `validate-lint` job to include `contents: read`, `packages: read`, and `statuses: write`.
=> XS✔ ◾ Updating .NET to v8.0.403

.github/workflows/build.yml, .github/workflows/release.yml, .vscode/launch.json, src/Directory.Build.props, src/TestCollateral/NoTransitiveDependencies/NoTransitiveDependencies.csproj
This updates various configuration files to change the target framework from .NET 8.0 to .NET 9.0. The changes affect build, release, and launch configurations.
Key changes include:
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L246-R246): Updated the `AssetPath` to use `net9.0` instead of `net8.0`.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L185-R185): Updated the `AssetPath` to use `net9.0` instead of `net8.0`.
* [`.vscode/launch.json`](diffhunk://#diff-bd5430ee7c51dc892a67b3f2829d1f5b6d223f0fd48b82322cfd45baf9f5e945L9-R9): Updated multiple entries to use `net9.0` instead of `net8.0` for the `program` path. …
=> XS✔ ◾ .NET 9 Update – Part 2

src/UnitTests/NuGetTransitiveDependencyFinder.UnitTests.ConsoleApp/Process/ProgramRunnerUnitTests.cs, src/UnitTests/NuGetTransitiveDependencyFinder.UnitTests/ProjectAnalysis/DependencyFinderTests.cs
This includes changes to improve the handling of regular expressions in unit tests by converting methods to properties. The most important changes involve modifying the `FilterRegex` and `MatchingProjectsRegex` methods to be properties and updating the relevant test cases accordingly.
Improvements to regular expression handling:
* [`src/UnitTests/NuGetTransitiveDependencyFinder.UnitTests.ConsoleApp/Process/ProgramRunnerUnitTests.cs`](diffhunk://#diff-859b57afdfdd5c40a9e56cbf1a49b66c88b8e246d86e273414f01b34dca431dbR46-R51): Converted the `FilterRegex` method to a static partial property and updated its usage in the `Run_Called_PerformsExpectedActions` test method. [[1]](diffhunk://#diff-859b57afdfdd5c40a9e56cbf1a49b66c88b8e246d86e273414f01b34dca431dbR46-R51) …
=> XS✔ ◾ .NET 9 – Code Modernization
